<x-guide-layout>
    @include('guide.sections.intro')
    @include('guide.sections.lahan')
    @include('guide.sections.team')
    @include('guide.sections.plot')
    @include('guide.sections.progress')
    @include('guide.sections.anggaran')
    @include('guide.sections.pohon')  
    @include('guide.sections.gudang')
    @include('guide.sections.faq')
</x-guide-layout>